config/routes.rb
Rails.application.routes.draw do

  devise_for :users do
  get '/users/sign_out' => 'devise/session#destroy'
  end
resources :restaurants do
	resources :foods do
		resources :reviews
	end
end
	get '/profile' => 'pages#profile'
	root to: 'pages#home'

  get '/about' => 'pages#about'

  get '/contact' => 'pages#contact'

  get '/foodfight/' => 'pages#foodfight'
  
  post '/findresto' => 'pages#findresto'
 

  get '/login' => 'pages#login'

end

app/models/food.rb
class Food < ActiveRecord::Base
	belongs_to :restaurant
	has_many :reviews
	
  has_attached_file :avatar, :styles => { :large => "250x250", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :foods
	
	has_attached_file :avatar, :styles => { :tile => "280x200", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :food
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :reviews
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

def index
if current_user == nil
	redirect_to root_path
elsif current_user.email.include? 'admin@admin.com'
	@restaurant = Restaurant.find(params[:restaurant_id])
else
	redirect_to root_path
end

end

def new
	if current_user.email.include? 'admin@admin.com'
		@restaurant = Restaurant.find(params[:restaurant_id])
		@food = Food.new
	else 
		redirect_to root_path
	end
end

def create
@restaurant = Restaurant.find(params[:restaurant_id])
@food = Food.new ( food_params)
@food.name = params[:food][:name]
@food.price = params[:food][:price]
@food.description = params[:food][:description]
@food.save!

@restaurant.foods << @food
@restaurant.save!

redirect_to :restaurant_foods
end

def show
@restaurant = Restaurant.find(params[:restaurant_id])
@food = Food.find(params[:id])
end

def edit
if current_user.email.include? 'admin@admin.com'
	@restaurant = Restaurant.find(params[:restaurant_id])
	@food = Food.find(params[:id])
else
	redirect_to root_path
	end
end

def update
@restaurant = Restaurant.find(params[:restaurant_id])
@food = Food.find(params[:id])
@food.name = params[:food][:name]
@food.price = params[:food][:price]
@food.description = params[:food][:description]
@food.save!

redirect_to :restaurant_foods
end

def destroy
if current_user.email.include? 'admin@admin.com'
@restaurant = Restaurant.find(params[:restaurant_id])
	@food = Food.find(params[:id])
	@food.destroy!
	redirect_to :action => :index
else
	redirect_to root_path
end
end

private

def food_params
	params.require(:food).permit(:avatar)
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

 def home
	if current_user == nil
	@restaurants = Restaurant.all
	elsif current_user.email.include? 'admin@admin.com'
	redirect_to restaurants_path	
	else
	@restaurants = Restaurant.all
	end
  end
  
	def profile
		@user = current_user
		
	end
  def about
  end

  def contact
  end

  def foodfight
	@restaurants = Restaurant.all
  end
  
  def findresto
	@restaurant = Restaurant.find(params[:restaurant_id])
	@restaurant2 = Restaurant.find(params[:restaurant_id2])
  end
  
  
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
before_action :authenticate_user!

def index
if current_user.email.include? 'admin@admin.com'
	@restaurants = Restaurant.all
	else
		redirect_to root_path
	end
end

def new
if current_user == nil
	redirect_to root_path
elsif current_user.email.include? 'admin@admin.com'
	@restaurant = Restaurant.new
else
	redirect_to root_path
end

end
  
def create
	@restaurant = Restaurant.new( restaurant_params )
	@restaurant.name = params[:restaurant][:name]
	@restaurant.contact = params[:restaurant][:contact]
	@restaurant.address = params[:restaurant][:address]
	@restaurant.description = params[:restaurant][:description]
	#@restaurant.foods = []
	@restaurant.save!
	
	redirect_to :restaurants
end

def show
	@restaurant = Restaurant.find(params[:id])

end

def edit
if current_user == nil
	redirect_to root_path
elsif current_user.email.include? 'admin@admin.com'
	@restaurant = Restaurant.find(params[:id])
else
	redirect_to root_path
	end
end

  def update
	@restaurant = Restaurant.find(params[:id])
	@restaurant.name = params[:restaurant][:name]
	@restaurant.contact = params[:restaurant][:contact]
	@restaurant.address = params[:restaurant][:address]
	@restaurant.description = params[:restaurant][:description]
	@restaurant.save!
	@restaurants = Restaurant.all
	render :index
  end
  
    def destroy
	@restaurant = Restaurant.find(params[:id])
	@restaurant.destroy!
	redirect_to :action => :index

  end
  
  private
  
  def restaurant_params
	params.require(:restaurant).permit(:avatar)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :authenticate_user!

  def index
	@restaurant = Restaurant.find(params[:restaurant_id])
	@food = Food.find(params[:food_id])
  end
	
  def new
	@restaurant = Restaurant.find(params[:restaurant_id])
	@food = Food.find(params[:food_id])
	@review = Review.new
  end
  
  def create
	@restaurant = Restaurant.find(params[:restaurant_id])
	@food = Food.find(params[:food_id])
	@review = Review.new
	
	@user = current_user
	
	@review.content = params[:review][:content]
	@review.posted_on = DateTime.now
	@review.rating = params[:review][:rating]
	@review.user = current_user
	
	@review.save!	
	
	
	@food.reviews << @review
	
	#TO ADD RATING TO FOOD
	@food.rating = 0
	@food.reviews.each do |r| #for all the reviews of the specific food.. add it to x
		@food.rating = @food.rating.to_i + r.rating.to_i
	end
	
	@food.rating = @food.rating.to_i / (@food.reviews.count )
	
	@food.save!
	
	#TO ADD RATING TO Restaurant
	@restaurant.rating = 0
	@restaurant.foods.each do |f|
		@restaurant.rating = @restaurant.rating.to_i + f.rating.to_i
	end
	
	@restaurant.rating = @restaurant.rating.to_i / (@restaurant.foods.count)
	
	@restaurant.save!
	
	#END
	
	@user.reviews << @review
	@user.save!
	
	redirect_to restaurant_food_path(@restaurant.id, @food.id)
  end
  
  def edit
	@restaurant = Restaurant.find(params[:restaurant_id])
	@food = Food.find(params[:food_id])
	@review = Review.find(params[:id])
  end
  
  def update
	@restaurant = Restaurant.find(params[:restaurant_id])
	@food = Food.find(params[:food_id])
	@review = Review.find(params[:id])
	
	@review.content = params[:review][:content]
	@review.posted_on = DateTime.now
	@review.rating = params[:review][:rating]
	
	@review.save!
	
	redirect_to restaurant_food_path(@restaurant.id, @food.id)
  end
  
  def destroy
	@restaurant = Restaurant.find(params[:restaurant_id])
	@food = Food.find(params[:food_id])
	@review = Review.find(params[:id])
	@review.destroy!
	
	
	#GET THE REVIEW OF FOOD
	@food.rating = 0
	
	@food.reviews.each do |r| #for all the reviews of the specific food.. add it to x
		@food.rating = @food.rating.to_i + r.rating.to_i
	end
	
	if @food.reviews.count == 0
		@food.rating = 0
		
	else
		@food.rating = @food.rating.to_i / (@food.reviews.count)
	end
	@food.save!
	
	#GET THE REVIEW OF RESTO
	@restaurant.rating = 0
	
	@restaurant.foods.each do |f|
		@restaurant.rating = @restaurant.rating.to_i + f.rating.to_i
	end
	
	@restaurant.rating = @restaurant.rating.to_i / (@restaurant.foods.count)
	
	@restaurant.save!
	
	
	redirect_to restaurant_food_path(@restaurant.id, @food.id)
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/foods/edit.html.erb
<h1>Editing Food <%= @food.name %> of <%= @restaurant.name %></h1>
<%= render :partial => 'form' %>

app/views/foods/index.html.erb
<h1>List of Foods of <%= @restaurant.name %></h1>
<table class="table">
	<thead>
		<tr>
			<td>Id</td>
			<td>Name</td>
			<td>Price</td>
			<td>Rating</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	</thead>
	
	<tbody>
	<% @restaurant.foods.each do |f| %>
	<tr>
		<td><%= f.id %></td>

		<td><%= f.name %></td>
		<td><%= f.price %></td>
		<td><%= f.rating %></td>
		<td><%= link_to "Edit", edit_restaurant_food_path(@restaurant.id, f.id) %></td>
		<td><%= button_to "Delete", [@restaurant, f], :method => :delete %></td>
	</tr>
	<% end %>
	</tbody>
	</table>
	<%= link_to "Add New Food", new_restaurant_food_path(@restaurant.id) %>
	&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
	<%= link_to "Back to the Restaurants", restaurants_path %>

app/views/foods/show.html.erb
<div class="navbar">
	<ul>
		<li><%= link_to "Food Fight!", root_path %></li> |
		<li class="active"><%= link_to "Home", root_path %></li>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Contact", contact_path %></li>
		<li><%= link_to "Food Fight!", foodfight_path %></li>
		<li id="login"><% if user_signed_in? %>
		Logged in as <strong><%= current_user.email %></strong> |
		
		<%= link_to "Logout", destroy_user_session_path, method: :delete %>
		<% else %>
		<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
		<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %></li>
	</ul>
</div>	

<div class="content2">
	<div class="heading">
		<h1> <%= @restaurant.name %>'s <%= @food.name %></h1>
	</div>

<% @food.reviews.each do |r| %>
<div class="reviewcontent">
	<div class="reviewheader">
		<h3><u><%= r.user.email %></u></h3>
	</div>
	
	<div class="reviewinfo">
		<h5>Posted on: <%= r.posted_on %></h5>
		<h5>Rating: <%= r.rating %></h5>
	</div>
	
	<br /><br /><br /><br />
	<div class="wordsreview">
		<%= r.content %>
	</div>
<br />
<br />
<br />
		<div class="addedoptions">
		<% if current_user.id == r.user_id %>
		
		<p><%= link_to "Edit", edit_restaurant_food_review_path(@restaurant.id, @food.id, r.id) %>
		<%= button_to "Delete", [@restaurant, @food, r], :method => :delete %></p>
		<% end %>
		</div>
</div>
<br /><br /><br />
<% end %>

<br />
</div>

<div class="bottomlink">
<%= link_to "Return to food list", restaurant_path(@restaurant.id) %>
</div>

app/views/pages/about.html.erb
<body>
<div class="navbar">
	<ul>
		<li><%= link_to "Food Fight!", root_path %></li> |
		<li><%= link_to "Home", root_path %></li>
		<li class="active"><%= link_to "About", about_path %></li>
		<li><%= link_to "Contact", contact_path %></li>
		<li><%= link_to "Battle", foodfight_path %></li>
		<li id="login"><% if user_signed_in? %>
		Logged in as <strong><%= current_user.email %></strong> |
		
		<%= link_to "Logout", destroy_user_session_path, method: :delete %>
		<% else %>
		<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
		<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %></li>
	</ul>
</div>


<div class="content2">
	<div class="heading">
		<h1>About Us</h1>
	</div>
	<br />
	<br />
	<div class="words">
	<p><span class="emphasize">Food Fight</span> is a project created by 3rd year MIS students namely Marty Geronimo and Justine Young. The purpose of this website is to inform and guide everyone on where to eat,
	what is the best dish, and other details like how much it costs. What makes this site different is that we offer users an avenue to compare and contrast different dishes to help them decide
	where to eat. Through FoodFight.com, one can find the best of the best dishes the world has to offer.</p>
	</div>
</div>

app/views/pages/contact.html.erb
<body>
<div class="navbar">
	<ul>
		<li><%= link_to "Food Fight!", root_path %></li> |
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "About", about_path %></li>
		<li class="active"><%= link_to "Contact", contact_path %></li>
		<li><%= link_to "Battle", foodfight_path %></li>
		<li id="login"><% if user_signed_in? %>
		Logged in as <strong><%= current_user.email %></strong> |
		
		<%= link_to "Logout", destroy_user_session_path, method: :delete %>
		<% else %>
		<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
		<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %></li>
	</ul>
</div>


<div class="content2">
	<div class="heading">
		<h1>Contact Us</h1>
	</div>
	
	<br /><br />
	<div class="words">
	<p><span class="emphasize">Telephone:</span>&nbsp 4-FOOD or 4663</p>
	<p><span class="emphasize">Email:</span>&nbsp foodfight@nanaymo.com</p>
	<p><span class="emphasize">Facebook:</span>&nbsp www.facebook.com/mattsgeronimo</p>
	<p><span class="emphasize">Twitter:</span>&nbsp twitter.com/martygeronimo69 </p>
	<p><span class="emphasize">Visit Us:</span>&nbsp Douchebag capital of the Philippines, Tarlac! </p>
	</div>
</div>

app/views/pages/findresto.html.erb
<body>
<div class="navbar">
	<ul>
		<li><%= link_to "Food Fight!", root_path %></li> |
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Contact", contact_path %></li>
		<li class="active"><%= link_to "Battle", foodfight_path %></li>
		<li id="login"><% if user_signed_in? %>
		Logged in as <strong><%= current_user.email %></strong> |
		
		<%= link_to "Logout", destroy_user_session_path, method: :delete %>
		<% else %>
		<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
		<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %></li>
	</ul>
</div>

<div class="content2">
	<div class="heading">
		<h1>Food Fight!!</h1>
	</div>
	
	<div class="leftpart">

			<div class="icon">
				<%= image_tag @restaurant.avatar.url%>
			</div>
		
			<div class="info">
				<h4 style="color:#00AAB2;"><%= @restaurant.name %></h4>
				<h4>Contact: <%= @restaurant.contact %></h4>
				<h4>Address: <%= @restaurant.address %></h4>
				<h4>Rating: <%= @restaurant.rating %></h4>
			</div>
			

		<% @restaurant.foods.each do |f| %>
		<div class="foodlist">
			<div class="foodlistcontent">
				<div class="thumb2">
					<%= image_tag f.avatar.url(:medium) %></li>
				</div>
			
				<div class="details2">
					<h4 style="color:#00AAB2;"><%= f.name %></h3>
					<h4>Price:&nbsp<%= f.price %></h4>
					<h4>Description:&nbsp<%= f.description %></h4>
					<h4>Rating:&nbsp<%= f.rating %></h4>
				</div>
			</div>
		</div>
		<% end %>
		
	</div>
	
	<div class="rightpart">
		<div class="icon">
			<%= image_tag @restaurant2.avatar.url(:medium) %>
		</div>
		
		<div class="info">
			<h4 style="color:#00AAB2;"><%= @restaurant2.name %></h4>
			<h4>Contact: <%= @restaurant2.contact %></h4>
			<h4>Address: <%= @restaurant2.address %></h4>
			<h4>Rating: <%= @restaurant2.rating %></h4>
		</div>
		
		<% @restaurant2.foods.each do |f| %>
		<div class="foodlist">
			<div class="foodlistcontent">
				<div class="thumb2">
					<%= image_tag f.avatar.url(:medium) %></li>
				</div>
			
				<div class="details2">
					<h4 style="color:#00AAB2;"><%= f.name %></h3>
					<h4>Price:&nbsp<%= f.price %></h4>
					<h4>Description:&nbsp<%= f.description %></h4>
					<h4>Rating:&nbsp<%= f.rating %></h4>
				</div>
			</div>
		</div>
		<% end %>
	</div>

app/views/pages/foodfight.html.erb
<body>
<div class="navbar">
	<ul>
		<li><%= link_to "Food Fight!", root_path %></li> |
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Contact", contact_path %></li>
		<li class="active"><%= link_to "Battle", foodfight_path %></li>
		<li id="login"><% if user_signed_in? %>
		Logged in as <strong><%= current_user.email %></strong> |
		
		<%= link_to "Logout", destroy_user_session_path, method: :delete %>
		<% else %>
		<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
		<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %></li>
	</ul>
</div>

<div class="content2">
	<div class="heading">
		<h1>Let The Battle Begin!</h1>
	</div>
	
	<div class="battle">
	
	<h2>
	<%= form_tag("/findresto", method: "post") do %>
	
	<%= select_tag "restaurant_id", options_from_collection_for_select(@restaurants, "id", "name") %>
	
	Versus
	
	
	<%= select_tag "restaurant_id2", options_from_collection_for_select(@restaurants, "id", "name") %>
	<div id="compare"><%= submit_tag("Go!") %></div>
	

	<% end %>
		</h2>
	</div>
	


</div>
</body>

app/views/pages/home.html.erb
<body>
<div class="navbar">
	<ul>
		<li><%= link_to "Food Fight!", root_path %></li> |
		<li class="active"><%= link_to "Home", root_path %></li>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Contact", contact_path %></li>
		<li><%= link_to "Battle", foodfight_path %></li>
		<li id="login"><% if user_signed_in? %>
		Logged in as <strong><a href = profile><%= current_user.email %></a></strong> |
		
		<%= link_to "Logout", destroy_user_session_path, method: :delete %>
		<% else %>
		<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
		<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %></li>
	</ul>
</div>

<div class="banner">
	<img src="/images/banners/Banner2.2.jpg">
</div>

<div class="content">
	<div class="heading">
		<h1>Featuring JSEC!</h1>
	</div>
	
	<% @restaurants.each do |r| %>
	
		<%= link_to restaurant_path(r.id) do %>
		<div class="tile">
			<div class="tilepic">
				<%= image_tag r.avatar.url(:medium) %>
			</div>
			<div class="tilecontent">
				<h4><%= r.description %></h4>
			</div>
		</div>
		<% end %>
	<% end %>
	
</div>

</body>

app/views/pages/profile.html.erb
<body>
<div class="navbar">
	<ul>
		<li><%= link_to "Food Fight!", root_path %></li> |
		<li><%= link_to "Home", root_path %></li>
		<li class="active"><%= link_to "About", about_path %></li>
		<li><%= link_to "Contact", contact_path %></li>
		<li><%= link_to "Battle", foodfight_path %></li>
		<li id="login"><% if user_signed_in? %>
		Logged in as <strong><%= current_user.email %></strong> |
		
		<%= link_to "Logout", destroy_user_session_path, method: :delete %>
		<% else %>
		<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
		<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %></li>
	</ul>
</div>

<div class="content3">
	<div class="heading">
		<h1>List of Your Reviews</h1>
	</div>

	<div class="words">
<table class="table">
	<thead>
		<tr>
			<td>Id</td>
			<td>Name</td>
			<td>Content</td>
			<td>Posted On</td>
		</tr>
	</thead>
	
	<tbody>
	<% @user.reviews.each do |f| %>
	<tr>
		<% if f.food == nil %>
		<td><%= f.id %></td>
		<td>Food no longer exists</td>
		<td></td>
		<td></td>
		<% else %>
		<td><%= f.id %></td>
		<td><%= f.food.name %></td>
		<td><%= f.content %></td>
		<td><%= f.posted_on %></td>
		<% end %>
		
	</tr>
	<% end %>
	</tbody>
	</table>
	
	</div>
</div>

app/views/restaurants/index.html.erb
<h1>List of Restaurants</h1>

<table class="table">
	<thead>
		<tr>
			<td>Id</td>
			<td>Name</td>
			<td>Address</td>
			<td>Contact</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	</thead>
	<tbody>
		<% @restaurants.each do |resto| %>
		<tr>
			<td><%= resto.id %></td>
			<td><%= link_to resto.name, resto %></td>
			<td><%= resto.address %></td>
			<td><%= resto.contact %></td>
			<td><%= link_to "Edit", edit_restaurant_path(resto.id) %></td>
			<td><%= link_to "Food List", restaurant_foods_path(resto.id) %></td>
			<td><%= button_to "Delete", resto, :method => :delete %></td>
			
		</tr>
		<% end %>
	</tbody>
</table>
<%= link_to 'Create New Restaurant', new_restaurant_path %>
<br />
<br />
<%= link_to "Logout", destroy_user_session_path, method: :delete %>

app/views/restaurants/show.html.erb
<body>
<div class="navbar">
	<ul>
		<li><%= link_to "Food Fight!", root_path %></li> |
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Contact", contact_path %></li>
		<li><%= link_to "Food Fight!", foodfight_path %></li>
		<li id="login"><% if user_signed_in? %>
		Logged in as <strong><%= current_user.email %></strong> |
		
		<%= link_to "Logout", destroy_user_session_path, method: :delete %>
		<% else %>
		<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
		<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %></li>
	</ul>
</div>

<div class="content2">
	<div class="heading">
		<h1><%= @restaurant.name %></h1>
	</div>
	
	<% @restaurant.foods.each do |f| %>
	<div class="food">
		<div class="thumb">
			<%= image_tag f.avatar.url(:medium) %></li>
		</div>
		
		<div class="details">
			<h3><%= f.name %></h3>
			<h4>Price:&nbsp<%= f.price %></h4>
			<h4>Description:&nbsp<%= f.description %></h4>
			<h4>Rating:&nbsp<%= f.rating %></h4>
			&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<%= link_to "Write Review", new_restaurant_food_review_path(@restaurant.id, f.id) %>
			&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<%= link_to "View Reviews", restaurant_food_path(@restaurant.id, f.id)%>
		</div>
	</div>
	<% end %>

</div>

app/views/reviews/edit.html.erb
<div class="navbar">
	<ul>
		<li><%= link_to "Food Fight!", root_path %></li> |
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Contact", contact_path %></li>
		<li><%= link_to "Food Fight!", foodfight_path %></li>
		
		<li class="login">
		<% if user_signed_in? %>
		
		Logged in as <strong><%= current_user.email %></strong>.
		
		<%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
		<% else %>
		<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> | 
		<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
		<% end %>
	</ul>
</div>

<div class="content2">
	<div class="heading">
		<h1>Edit Your Review</h1>
	</div>

	<br />
	<br />
	<br />
	<div class="words">
		<div class="form-inputs">
			<%= render :partial => 'form' %>
		</div>
</div>
</div>
		<div class="bottomlink">
<%= link_to "Return to food list", restaurant_path(@restaurant.id) %>
</div>

app/views/reviews/index.html.erb
<h1>List of your reviews.</h1>
<table class="table">
	<thead>
		<tr>
			<td>Id</td>
			<td>Name</td>
			<td>Content</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	</thead>
	
	<tbody>
	<% @user.reviews.each do |f| %>
	<tr>
		<td><%= f.id %></td>

		
		<td><%= f.content %></td>
		<td><%= f.posted_on %></td>
		
	</tr>
	<% end %>
	</tbody>
	</table>
	<%= link_to "Add New Food", new_restaurant_food_path(@restaurant.id) %>
	&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
	<%= link_to "Back to the Restaurants", restaurants_path %>

app/views/reviews/new.html.erb
<div class="navbar">
	<ul>
		<li><%= link_to "Food Fight!", root_path %></li> |
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Contact", contact_path %></li>
		<li><%= link_to "Food Fight!", foodfight_path %></li>
		<li id="login"><% if user_signed_in? %>
		Logged in as <strong><%= current_user.email %></strong> |
		
		<%= link_to "Logout", destroy_user_session_path, method: :delete %>
		<% else %>
		<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
		<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %></li>
	</ul>
</div>

<div class="content2">
	<div class="heading">
	<h1><%= @restaurant.name %>'s <%= @food.name %> </h1>
	</div>
	<br />
	<div class="words">
		<%= render :partial => 'form' %>
	</div>
</div>

<div class="bottomlink">
<%= link_to "Return to food list", restaurant_path(@restaurant.id) %>
</div>